version: "3.7"

x-log: &default
  restart: always
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

x-env-general: &env-general
  TZ: ${TZ:-Europe/Moscow}

x-env-elasticsearch: &env-elasticsearch
  MAX_LOCKED_MEMORY:                  ${MAX_LOCKED_MEMORY:-unlimited}
  ELASTICSEARCH_NODE_NAME:            ${ELASTICSEARCH_NODE_NAME:-{{.Task.Slot}}-elasticsearch-master}
  ELASTICSEARCH_CLUSTER_HOSTS:        ${ELASTICSEARCH_CLUSTER_HOSTS:-1-elasticsearch-master,2-elasticsearch-master,3-elasticsearch-master}
  ELASTICSEARCH_CLUSTER_NAME:         ${ELASTICSEARCH_CLUSTER_NAME:-elasticsearch-cluster-graylog}
  ELASTICSEARCH_HEAP_SIZE:            ${ELASTICSEARCH_HEAP_SIZE:-1g}
  ELASTICSEARCH_MINIMUM_MASTER_NODES: ${ELASTICSEARCH_MINIMUM_MASTER_NODES:-2}


x-env-graylog: &env-graylog
  # CHANGE ME (must be at least 16 characters)!
  GRAYLOG_PASSWORD_SECRET:                  ${GRAYLOG_PASSWORD_SECRET}
  GRAYLOG_IS_MASTER:                        ${GRAYLOG_IS_MASTER:-true}
  GRAYLOG_ROOT_PASSWORD_SHA2:               ${GRAYLOG_ROOT_PASSWORD_SHA2:-}
  GRAYLOG_HTTP_EXTERNAL_URI:                ${GRAYLOG_HTTP_EXTERNAL_URI}
  GRAYLOG_ELASTICSEARCH_VERSION:            ${GRAYLOG_ELASTICSEARCH_VERSION:-7}
  GRAYLOG_ELASTICSEARCH_HOSTS:              ${GRAYLOG_ELASTICSEARCH_HOSTS:-http://1-elasticsearch-master:9200,http://2-elasticsearch-master:9200,http://3-elasticsearch-master:9200}
  GRAYLOG_ELASTICSEARCH_SHARDS:             ${GRAYLOG_ELASTICSEARCH_SHARDS:-3}
  GRAYLOG_ELASTICSEARCH_REPLICAS:           ${GRAYLOG_ELASTICSEARCH_REPLICAS:-1}
  GRAYLOG_PROMETHEUS_EXPORTER_ENABLED:      ${GRAYLOG_PROMETHEUS_EXPORTER_ENABLED:-true}
  GRAYLOG_PROMETHEUS_EXPORTER_BIND_ADDRESS: ${GRAYLOG_PROMETHEUS_EXPORTER_BIND_ADDRESS:-0.0.0.0:9833}

x-env-db-backup: &env-db-backup
  DB_TYPE:          ${DB_TYPE:-mongo}
  DB_HOST:          ${DB_HOST:-mongo}
  DB_NAME:          ${DB_NAME:-all}
  DB_DUMP_FREQ:     ${DB_DUMP_FREQ:-1440}
  DB_DUMP_BEGIN:    ${DB_DUMP_BEGIN:-1900}
  DB_CLEANUP_TIME:  ${DB_CLEANUP_TIME:-8640}

services:
  elasticsearch:
    image: bitnami/elasticsearch:7.10.1
    <<: *default
    hostname: "{{.Task.Slot}}-elasticsearch-master"
    environment:
      <<: *env-elasticsearch
      <<: *env-general
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.backend == true
      replicas: 3
      resources:
        limits:
          memory: 2g
    security_opt:
      - no-new-privileges:true
    networks:
      - graylog

  mongo:
    image: mongo:4.2
    <<: *default
    environment:
      <<: *env-general
    volumes:
        - mongo_data:/data/db 
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.backend == true
      replicas: 1
      resources:
        limits:
          memory: 1g
    security_opt:
      - no-new-privileges:true
    networks:
      - graylog

  graylog:
    image: graylog/graylog:4.3
    <<: *default
    volumes:
      - graylog_data:/usr/share/graylog/data
    environment:
      <<: *env-graylog
      <<: *env-general
    ports:
      # Graylog web interface and REST API
      - 80:9000
      # Syslog TCP
      - 1514
      # Syslog UDP
      - 1514/udp
      # GELF TCP
      - 12201
      # GELF UDP
      - 12201/udp
      - 5555/udp
      # Дополнтельные порты
      - 30000-30020
      - 30000-30020/udp
      # Prometeus exporter
      - 9833:9833
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    security_opt:
      - no-new-privileges:true
    depends_on:
      - elasticsearch
      - mongo
    networks:
      - graylog

  fluentd-collector:
    image: ${fluentd_tags_build}
    <<: *default
    hostname: fluentd-collector
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1Gb
        reservations:
          memory: 100M 
    volumes:
      - ./fluentd-collector/fluent.conf:/fluentd/etc/fluent.conf
      - buffer:/var/log/fluent/
      - ./fluentd-collector/plugins:/fluentd/plugins:rw
    ports:
      # forward ports
      - "24224:24224"
      - "24224:24224/udp"
      # http check ports      
      - "8888:8888"
      # prometheus check ports
      - "24231:24231"
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    security_opt:
      - no-new-privileges:true
    networks:
      - graylog

  elasticsearch-exporter:
    image: bitnami/elasticsearch-exporter:latest
    <<: *default
    command:
      '--es.uri=http://elasticsearch:9200'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          memory: 10M 
      mode: global
      placement:
        constraints: [node.role == manager]
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *env-general
    ports:
      - ${ES_EX_PORT:-9114}:9114
    networks:
      - graylog

  db-backup-mongo:
    image: tiredofit/db-backup
    <<: *default
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1Gb
        reservations:
          memory: 50M 
      mode: global
      placement:
        constraints: [node.role == manager]
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *env-general
    volumes:
      - backups:/backup
    networks:
      - graylog

networks:
  graylog:
    driver: overlay
    attachable: true

volumes:
  elasticsearch:
  buffer:
  graylog_data:
  mongo_data:
  backups: